/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as InboundRouteImport } from './routes/inbound'
import { Route as TonightRouteImport } from './routes/tonight'
import { Route as BookTokenRouteImport } from './routes/book.$token'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as BookingReturnRouteImport } from './routes/booking.return'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as ApiPublicHooksDailyRouteImport } from './routes/api/public/hooks/daily'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundRoute = InboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const TonightRoute = TonightRouteImport.update({
  id: '/tonight',
  path: '/tonight',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTokenRoute = BookTokenRouteImport.update({
  id: '/book/$token',
  path: '/book/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingReturnRoute = BookingReturnRouteImport.update({
  id: '/booking/return',
  path: '/booking/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyRoute = ApiPublicHooksDailyRouteImport.update({
  id: '/api/public/hooks/daily',
  path: '/api/public/hooks/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/inbound': typeof InboundRoute
  '/tonight': typeof TonightRoute
  '/book/$token': typeof BookTokenRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/return': typeof BookingReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/api/public/hooks/daily': typeof ApiPublicHooksDailyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/inbound': typeof InboundRoute
  '/tonight': typeof TonightRoute
  '/book/$token': typeof BookTokenRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/return': typeof BookingReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/api/public/hooks/daily': typeof ApiPublicHooksDailyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/inbound': typeof InboundRoute
  '/tonight': typeof TonightRoute
  '/book/$token': typeof BookTokenRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/return': typeof BookingReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/api/public/hooks/daily': typeof ApiPublicHooksDailyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/inbound'
    | '/tonight'
    | '/book/$token'
    | '/booking/$id'
    | '/booking/return'
    | '/claim/$token'
    | '/api/public/hooks/daily'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/inbound'
    | '/tonight'
    | '/book/$token'
    | '/booking/$id'
    | '/booking/return'
    | '/claim/$token'
    | '/api/public/hooks/daily'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/inbound'
    | '/tonight'
    | '/book/$token'
    | '/booking/$id'
    | '/booking/return'
    | '/claim/$token'
    | '/api/public/hooks/daily'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  InboundRoute: typeof InboundRoute
  TonightRoute: typeof TonightRoute
  BookTokenRoute: typeof BookTokenRoute
  BookingIdRoute: typeof BookingIdRoute
  BookingReturnRoute: typeof BookingReturnRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  ApiPublicHooksDailyRoute: typeof ApiPublicHooksDailyRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound': {
      id: '/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tonight': {
      id: '/tonight'
      path: '/tonight'
      fullPath: '/tonight'
      preLoaderRoute: typeof TonightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$token': {
      id: '/book/$token'
      path: '/book/$token'
      fullPath: '/book/$token'
      preLoaderRoute: typeof BookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/return': {
      id: '/booking/return'
      path: '/booking/return'
      fullPath: '/booking/return'
      preLoaderRoute: typeof BookingReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily': {
      id: '/api/public/hooks/daily'
      path: '/api/public/hooks/daily'
      fullPath: '/api/public/hooks/daily'
      preLoaderRoute: typeof ApiPublicHooksDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  InboundRoute: InboundRoute,
  TonightRoute: TonightRoute,
  BookTokenRoute: BookTokenRoute,
  BookingIdRoute: BookingIdRoute,
  BookingReturnRoute: BookingReturnRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  ApiPublicHooksDailyRoute: ApiPublicHooksDailyRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
